version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME:-cekuai-app}
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:${APP_INTERNAL_PORT:-3000}"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: ${APP_INTERNAL_PORT:-3000}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
