name: Deploy to OCI (Production)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/oci_key
        chmod 600 ~/.ssh/oci_key
        ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to OCI Production
      run: |
        ssh -i ~/.ssh/oci_key ubuntu@${{ secrets.OCI_HOST }} bash <<'ENDSSH'
          set -euo pipefail

          cd /home/ubuntu
          mkdir -p cekuai
          cd cekuai

          if [ -d .git ]; then
            git fetch --all --prune
            git reset --hard origin/main
          else
            git clone https://github.com/cekuaione/cekuai.git .
            git checkout main
          fi

          # Create .env file from GitHub Secrets
          printf "%s\n" \
            "EXERCISEDB_API_KEY=${{ secrets.EXERCISEDB_API_KEY }}" \
            "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
            "NEXT_PUBLIC_API_URL=http://${{ secrets.OCI_HOST }}:3000" \
            "NEXTAUTH_URL=http://${{ secrets.OCI_HOST }}:3000" \
            "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" \
            "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" \
            "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
            "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            "UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}" \
            "UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" \
            "N8N_URL=${{ secrets.N8N_URL }}" \
            "N8N_API_KEY=${{ secrets.N8N_API_KEY }}" \
            "OCI_ACCESS_KEY_ID=${{ secrets.OCI_ACCESS_KEY_ID }}" \
            "OCI_SECRET_ACCESS_KEY=${{ secrets.OCI_SECRET_ACCESS_KEY }}" \
            "OCI_ENDPOINT=${{ secrets.OCI_ENDPOINT }}" \
            "OCI_BUCKET_NAME=${{ secrets.OCI_BUCKET_NAME }}" \
            "OCI_REGION=${{ secrets.OCI_REGION }}" \
            "N8N_SOCIAL_MEDIA_WEBHOOK_URL=${{ secrets.N8N_SOCIAL_MEDIA_WEBHOOK_URL }}" \
          > .env

          export APP_CONTAINER_NAME=cekuai-app
          export APP_PORT=3000
          export APP_INTERNAL_PORT=3000

          docker compose down --remove-orphans || true
          docker compose build --pull
          docker compose up -d

          echo "⏳ Waiting for app container to report running state..."
          state=""
          for attempt in $(seq 1 12); do
            state=$(docker compose ps --format '{{.State}}' app 2>/dev/null || true)
            if [[ "$state" == running* ]]; then
              break
            fi
            sleep 10
          done

          if [[ "$state" != running* ]]; then
            echo "❌ App container failed to reach running state (state: ${state:-unknown})."
            docker compose ps
            docker compose logs --no-color
            exit 1
          fi

          docker compose ps
          docker compose logs --tail 100
        ENDSSH
    
    - name: Cleanup old Docker images
      run: |
        ssh -i ~/.ssh/oci_key ubuntu@${{ secrets.OCI_HOST }} '
          echo "🧹 Cleaning up old Docker images..."
          docker images --format "{{.Repository}}:{{.Tag}}\t{{.ID}}\t{{.CreatedAt}}" | 
          grep cekuai | 
          sort -k3 -r | 
          tail -n +4 | 
          awk "{print \$2}" | 
          xargs -r docker rmi -f || true
          echo "✅ Docker image cleanup completed"
        '
      continue-on-error: true
    
    - name: Display info
      run: |
        echo "✅ Production deployed!"
        echo "🌐 http://${{ secrets.OCI_HOST }}:3000"
