name: Deploy to OCI (Production)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/oci_key
        chmod 600 ~/.ssh/oci_key
        ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to OCI Production
      env:
        EXERCISEDB_KEY: ${{ secrets.EXERCISEDB_API_KEY }}
        OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
        OCI_IP: ${{ secrets.OCI_HOST }}
      run: |
        ssh -i ~/.ssh/oci_key ubuntu@${{ secrets.OCI_HOST }} bash << 'ENDSSH'
          cd /home/ubuntu/cekuai || mkdir -p /home/ubuntu/cekuai
          cd /home/ubuntu/cekuai
          
          if [ -d .git ]; then
            git pull origin main
          else
            git clone https://github.com/cekuaione/cekuai.git .
          fi
          
          echo "EXERCISEDB_API_KEY=${{ secrets.EXERCISEDB_API_KEY }}" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_API_URL=http://${{ secrets.OCI_HOST }}:3000" >> .env
          
          docker-compose down || true
          docker-compose up -d --build
          docker image prune -af
          docker ps
        ENDSSH
    
    - name: Verify deployment
      run: |
        sleep 15
        curl -f http://${{ secrets.OCI_HOST }}:3000 || exit 1
